# we don't need SSL here, let's disable it to have a more compact native executable
quarkus.ssl.native=false

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.packages=org.acme.hibernate.search.elasticsearch.model
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-search-orm.elasticsearch.version=7
quarkus.hibernate-search-orm.automatic-indexing.synchronization.strategy=sync

quarkus.datasource."other".db-kind=postgresql
quarkus.hibernate-orm."other".packages=org.acme.hibernate.search.elasticsearch.otherpu
quarkus.hibernate-orm."other".datasource=other
quarkus.hibernate-orm."other".sql-load-script=import2.sql
quarkus.hibernate-search-orm."other".elasticsearch.version=7.17
quarkus.hibernate-search-orm."other".automatic-indexing.synchronization.strategy=sync
quarkus.hibernate-search-orm."other".schema-management.strategy=none
quarkus.hibernate-search-orm."other".elasticsearch.version-check.enabled=false

%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
%prod.quarkus.datasource.username=quarkus_test
%prod.quarkus.datasource.password=quarkus_test
%prod.quarkus.hibernate-orm.database.generation=create
%prod.hibernate-search-orm.elasticsearch.hosts=localhost:9200