quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

# Workaround for https://github.com/quarkusio/quarkus/issues/33104
quarkus.datasource.devservices.container-env."PERSISTENT_HOME"=false

# No more than 8 characters for the instance name
%prod.quarkus.datasource.username=quarkus
%prod.quarkus.datasource.password=quarkus
%prod.quarkus.datasource.jdbc.url=jdbc:db2://localhost:50000/quarkus
%prod.quarkus.hibernate-orm.schema-management.strategy=create
