%dev.quarkus.hibernate-orm.database.generation=none
%dev.quarkus.datasource.devservices.init-script-path=/init.sql
%dev.quarkus.datasource.devservices.reuse=false

# If you have a container image for Oracle 19, set the image name through env. variables
%dev.quarkus.datasource.devservices.image-name=${ORACLE_19_CONTAINER:gvenzl/oracle-xe:21.3.0-slim}

quarkus.datasource.db-version=19.0
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

%prod.quarkus.datasource.username=quarkus_test
%prod.quarkus.datasource.password=quarkus_test
%prod.quarkus.datasource.jdbc.url=jdbc:oracle://localhost/quarkus_test
%prod.quarkus.hibernate-orm.database.generation=create