quarkus.http.port=8080
%dev.quarkus.http.port=8083

quarkus.datasource."DB1".db-kind=postgresql
quarkus.datasource."DB1".username=user1
quarkus.datasource."DB1".password=password1
%dev.quarkus.datasource."DB1".jdbc.url=jdbc:postgresql://localhost:5432/db1

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm."DB1".datasource=DB1
quarkus.hibernate-orm."DB1".database.default-schema=DB1
quarkus.hibernate-orm."DB1".discriminator.ignore-explicit-for-joined=true
quarkus.hibernate-orm."DB1".fetch.max-depth=1
quarkus.hibernate-orm."DB1".packages=org.acme.hibernate.orm.package1
quarkus.hibernate-orm."DB1".database.generation=none
quarkus.hibernate-orm."DB1".validate-in-dev-mode=false

quarkus.datasource."DB2".db-kind=postgresql
quarkus.datasource."DB2".username=user2
quarkus.datasource."DB2".password=password2
%dev.quarkus.datasource."DB2".jdbc.url=jdbc:postgresql://localhost:5432/db2

quarkus.hibernate-orm."DB2".datasource=DB2
quarkus.hibernate-orm."DB2".database.default-schema=DB2
quarkus.hibernate-orm."DB2".discriminator.ignore-explicit-for-joined=true
quarkus.hibernate-orm."DB2".fetch.max-depth=1
quarkus.hibernate-orm."DB2".packages=org.acme.hibernate.orm.package2
quarkus.hibernate-orm."DB2".database.generation=none
quarkus.hibernate-orm."DB2".validate-in-dev-mode=false
